### ISSUE TITLE
Decidí entrar a la cueva y no ocurre nada

### ISSUE THREAD

**Issue by ekauffmann** [vgdev-beauchef/Wilson#1]
Para repetir bug:

1.- comer 2 crías de jabalí
2.- tomar cuchillo del cadaver y matar a la madre jabalí
3.- ir a la cueva y pararme en la "o" azul. 
4.- decidir entrar

luego de eso el juego sigue. Puedo moverme y al dirigirme a la cueva nada ocurre

**Comment by aantoine** [comment]
fixed
